# -*- coding: utf-8 -*-
"""Лаб. 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tj5P4EDQSKYjQajLe-rFB0lXEvqQOM4R
"""

def foo(a):
    """!!!

    Сложность: !!!.
    """
    for i in range(len(a), 0, -1): # O(len(a))
        for j in range(1, i): # O(N)
            if a[j-1] > a[j]: # O(1)
                a[j-1], a[j] = a[j], a[j-1] # O(1)
    return a


a = [1, 2, 3, 4, 2, 1, 3, 4, 3, 5, -2, -2, 2, -2, 65, 2, 2]
foo(a)

def foo(i):
    """!!!

    Параметры:
        - i (int): число.

    Сложность: !!!.
    """
    digits = "0123456789"
    if i == 0: # O(1)
        return "0"
    result = ""
    while i > 0: # O(N)
        result = digits[i%10] + result
        i = i // 10
    return result

i = 7998
foo(i)

def foo(s):
    """!!!

    Параметры:
        - s (str): строка.

    Сложность: !!!.
    """
    val = 0
    for c in s: # O(N)
        if c.isdigit(): # O(1)
            val += int(c)
    return val

s = '87'
foo(s)

def foo(n):
    """!!!

    Параметры:
        - n (int): число.

    Сложность: !!!.
    """
    res = []
    for i in range(1, n + 1): #O(N)
        divisors = 0
        j = 2
        while j < i and divisors == 0: # O(1)
            if i % j == 0: # O(1)
                divisors += 1
            j += 1

        if divisors == 0: # O(1)
            res.append(i)

    return res

n = 13
foo(n)

def foo(nums):
    """!!!

    Параметры:
        - nums (list): список.

    Сложность: !!!.
    """
    for x in nums: # O(1)
        if x % 2 == 0: # O(1)
            return True
    else:
        return False

nums = [1, 3, 5, 6]
foo(nums)

def foo(nums):
    """!!!

    Параметры:
        - nums (list): список.

    Сложность: !!!.
    """
    return (nums[0] + nums[-1] ** 2) # O(1)

nums = [2, 2, 7, -9]
foo(nums)